### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by rituparnadobey-dci**

### CODE REVIEW

**Comment by rituparnadobey-dci** [comment]
All okay

**Comment by rituparnadobey-dci** [comment]
all okay

**Comment by RituparnaDobey** [comment]
close it

**Comment by rituparnadobey-dci** [comment]
yes

**Comment by RituparnaDobey** [comment]
wow

**Comment by rituparnadobey-dci** [comment]
omg

**Review by rituparnadobey-dci — COMMENTED** [review]
okay

**Review by RituparnaDobey — COMMENTED** [review]
yes

**Pull request closed without merging**
